import type { ModuleDefinition, ModuleType } from './ModuleDefinition'

export const MODULE_DEFINITIONS: Record<ModuleType, ModuleDefinition> = {
  wood: {
    type: 'wood',
    name: '木质船体块',
    shortName: '船体',
    description: '轻量基础结构，适合搭建船体主体。',
    mass: 1.0,
    buoyancy: 1.4,
    durability: 100,
    drag: 1.0,
    color: '#9a6a3f',
    tags: ['Light', 'Hull', 'Basic'],
  },
  buoyancy: {
    type: 'buoyancy',
    name: '浮力块',
    shortName: '浮力',
    description: '提供高浮力，适合放在底部或两侧。',
    mass: 0.5,
    buoyancy: 2.4,
    durability: 60,
    drag: 1.2,
    color: '#78d7ff',
    emissive: '#0e6f9d',
    tags: ['Buoyant', 'Light', 'Float'],
  },
  ballast: {
    type: 'ballast',
    name: '压载块',
    shortName: '压载',
    description: '很重，放在底部能降低重心并提升稳定性。',
    mass: 3.5,
    buoyancy: 0.2,
    durability: 150,
    drag: 1.1,
    color: '#343944',
    tags: ['Heavy', 'Stable', 'Low Center'],
  },
  metal: {
    type: 'metal',
    name: '金属结构块',
    shortName: '金属',
    description: '坚固但偏重，过多使用会增加下沉风险。',
    mass: 2.2,
    buoyancy: 0.4,
    durability: 220,
    drag: 1.0,
    color: '#75818e',
    tags: ['Armor', 'Heavy', 'Strong'],
  },
  engine: {
    type: 'engine',
    name: '引擎模块',
    shortName: '引擎',
    description: '提供推进能力，适合放在船尾或中后部。',
    mass: 2.6,
    buoyancy: 0.3,
    durability: 120,
    drag: 1.2,
    thrust: 8.0,
    color: '#272d34',
    emissive: '#2f9dff',
    tags: ['Engine', 'Thrust', 'Heavy'],
  },
  rudder: {
    type: 'rudder',
    name: '船舵模块',
    shortName: '船舵',
    description: '提供转向能力，报告中会识别操控能力。',
    mass: 0.8,
    buoyancy: 0.5,
    durability: 80,
    drag: 1.0,
    turnPower: 1.0,
    color: '#253b4d',
    tags: ['Control', 'Steering'],
  },
  cannon: {
    type: 'cannon',
    name: '大炮模块',
    shortName: '大炮',
    description: '高处重物，会明显提高翻覆风险。',
    mass: 3.0,
    buoyancy: 0.1,
    durability: 150,
    drag: 1.0,
    recoil: 2.0,
    color: '#41464d',
    tags: ['Weapon', 'Heavy', 'Risky Top Weight'],
  },
  cargo: {
    type: 'cargo',
    name: '货物模块',
    shortName: '货物',
    description: '纯负载，用于测试承载能力和吃水深度。',
    mass: 2.8,
    buoyancy: 0.2,
    durability: 80,
    drag: 1.0,
    color: '#b68043',
    tags: ['Cargo', 'Heavy', 'Load'],
  },
}

export const MODULE_ORDER: ModuleType[] = [
  'wood',
  'buoyancy',
  'ballast',
  'metal',
  'engine',
  'rudder',
  'cannon',
  'cargo',
]

